- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add issue templates to initial set up branch.
> Add issue templates ❗

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- CONTRIBUTING.md
- LICENSE
- README.md
This pull request includes:
- README
- Contributing Guidelines
- Pull request template
- Issue templates for bug report and feature request
- LICENSE
> Set up repository guidelines ⚡️

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- api/.eslintrc.json
- api/.prettierrc
- api/README.md
- api/app.js
- api/package.json
- api/public/stylesheets/style.css
- api/routes/index.js
- api/routes/testAPI.js
- api/routes/users.js
- api/src/testAPI.js
- api/src/users.js
- api/views/error.jade
- api/views/index.jade
- api/views/layout.jade
- client/.eslintrc.json
- client/README.md
- client/package.json
- client/src/App.js
- client/yarn.lock
This pull request
- Cleans excess functionality in `/api` directory
- Adds documentation for installing and running client and api
- Fixes current flow errors
> 🔥📖 Finalize project set up, improve documentation

- api/app.js
- api/package.json
- client/package.json
This pull request:
- Improve naming for different package json
- Matches versioning
- Removes jade view engine from api
> 🐣Package json improvement, remove jade usage

- api/src/models/category.js
- api/src/models/resource.js
This PR adds a schema to represent one category with many subcategories.
> 🐱 Add category schema

- client/src/components/Filter.js
- client/src/components/FilterCategory.js
Connecting the filter component to backend endpoints [part 1]
> 🥺Connect filter to backend

- client/src/components/Filter.js
Fix checking if resource's available languages contains given language string when applying a language filter
> 👌Fix Filtering

- client/src/components/Filter.js
- client/src/components/FilterHeader.js
- client/src/components/FilterPreview.js
- client/src/components/ResourceBreadcrumb.js
- now.json
This PR:
* Converts the existing filter page to use ant design components
* Converts FilterPreview to a functional component
* Starts styling the header of the filtering page
> 💅 Improve filter UI page

- client/src/components/Filter.js
- client/src/components/ResourceViewGrid.js
- client/src/css/ResourceViewFilterHeader.css
This PR:
* Adds some elements of responsiveness to the grid - there will either be one or three columns, based on the width of the window/device used
* Fixes the weird situation where there would be "blank" columns by adding the `flex` type to `Row`
* Deletes some unneeded code for toggling on the resource view page
* Edits some spacing
> 💆 Change grid to be more responsive

- client/src/components/ResourcePreview.js
- client/src/components/mobile/NavigationMobile.js
- client/src/css_mobile/Navigation.css
This PR:
* Conditionally renders the photo on the resource card, depending on whether the user is on mobile or desktop
* Edits the mobile nav CSS to apply only to the nav id (Resolves #91)
> 💇 Add conditionally rendering photo

- client/src/components/ResourceDetail.js
Resolves #89 
This just picks the first category and subcategory to show in the breadcrumb.
> 🚑 Fix breadcrumb in resource detail

- client/src/components/Home.js
- client/src/components/desktop/HomeDesktop.js
- client/src/components/mobile/HomeMobile.js
- client/src/css/Home.css
- client/src/css_mobile/Home.css
> Home mobile

- client/src/components/Home.js
- client/src/components/Navigation.js
- client/src/components/PrivateRoute.js
- client/src/components/Register.js
- client/src/components/desktop/NavigationDesktop.js
- client/src/components/mobile/NavigationMobile.js
- client/src/css/Login.css
- client/src/css/Register.css
- client/src/utils/mobile.js
This PR:
- Fixes partners text on homepage for desktop (Resolves #97)
- Shows `/role-approval` page when logged in as an admin (Resolves #98)
- Fixes login and register page styling
- Removes some unused variables
> 🌴 General Improvements

- api/yarn.lock
- client/src/components/ResourceDetail.js
- client/yarn.lock
- Shows resource website on ResourceDetail page
- Shows resource eligibility requirements on ResourceDetail page
- Upgrade yarn dependencies
> 🌋 Display resource website, eligibility on ResourceDetail

- client/src/pages/Register.js
- client/src/pages/RoleApproval.js
> 🎨 Convert Register.js and RoleApproval.js to functional components

- client/src/components/ResourceForm.js
- client/src/pages/Resources.js
- client/src/pages/RoleApproval.js
Resolves #108
Updated cost filter options on resources page and admin form
Fixed margins of role-changing form
Also yarn upgraded (oops)
Resource page:
Admin page:
Users page:
> 🆓 Supplement expense-filtering preferences with complimentary resources

- client/src/components/desktop/HomeDesktop.js
- client/src/css/Home.css
- client/src/css/Login.css
- client/src/pages/Login.js
- client/yarn.lock
> 🍮 Revitalize the appearance of various paraphernalia 

- client/src/pages/ResourceDetail.js
Resolves #113 
Default (no notes):
Please delete "Albert's therapy" resource when this is approved
> 🎶 Unveil clandestine commentary for administrators

- LICENSE
- README.md
- api/README.md
- api/package.json
- Add documentation about backend testing
- Update year for licensing
> 📖 Backend test documentation

- client/src/components/desktop/HomeDesktop.js
- client/src/components/desktop/NavigationDesktop.js
- client/src/components/desktop/ResourcesBanner.js
- client/src/css/Home.css
- client/src/css/Login.css
- client/src/css/Navigation.css
- client/src/css/Register.css
- client/src/css/ResourceDetail.css
- client/src/css/Resources.css
- client/src/css/ResourcesBreadcrumb.css
- client/src/css/ResourcesFilter.css
- client/src/css_mobile/Home.css
- client/src/css_mobile/ResourcesFilterMobile.css
- client/src/pages/Home.js
- client/src/pages/ResourceDetail.js
- client/yarn.lock
> 🎨 Design updates

- client/src/components/ResourcesBreadcrumb.js
Got rid of spaces in url when clicking breadcrumb.
Fixes #148
> 🍞 Fixed spaces in breadcrumb

- client/src/components/ResourcesBreadcrumb.js
- client/src/components/mobile/ResourcesFilterMobile.js
- client/src/css/ResourcesFilter.css
- client/src/css_mobile/ResourcesFilterMobile.css
- client/yarn.lock
Centers the search bar, adds space between the dropdowns.
If relevant, include:
Fixes #157 
Before:
After:
Ok I guess the before and after is not that useful.
> 🐱‍🐉 Mobile Resource Page Search Design Changes

- client/src/components/desktop/NavigationDesktop.js
- client/src/components/mobile/NavigationMobile.js
- Adds `exact` prop to Resources and Saved Resources
- Adds Saved Resources to navigation on mobile
Fixes #185, fixes #186
> 🦠 Fix navigation bugs

- client/src/css/Login.css
- client/src/css/Register.css
- client/src/pages/Login.js
- Fix color to match on login and registration
- Change font weight to normal
Fixes #182
> 🛑 Fix registration and login messages

- client/src/components/mobile/HomeMobile.js
- client/src/components/mobile/ResourcesBannerMobile.js
- client/src/css/Home.css
- client/src/css_mobile/Home.css
- client/src/css_mobile/ResourcesFilterMobile.css
- client/src/pages/Home.js
- Fix mobile home text
- Change mobile resource banner
- Make category drawer fill width
Closes #196, closes #200
> 📱 Update mobile design

- client/src/css/ResourcesFilter.css
- client/src/css_mobile/ResourcesFilterMobile.css
- Changed the text on the dropdown buttons to be slightly more vertically centered.
- Changed the text on the searchbar to be slightly more vertically centered.
- Expanded width of search bar (the text fully showed up on my screen, but just in case I still increased the width a little bit)
If relevant, include:
Fixes #192 
Screenshots:
Desktop-before:
Desktop-after:
-----------------------------------------------------------------------------------------------------------
Mobile-before:
Mobile-after:
> 🃏 Styling changes for the filter banner

- client/package.json
- client/src/pages/RoleApproval.js
Added a loading spinning symbol thingy for the user roles admin page while waiting for data to populate.
Fixes #199
> 🔃 Added loading icon for roles page

- api/src/app.js
Limit should be 2.1 mb, not 2.01 mb (2 mb + 100 kb = 2.1 mb lol i'm a disgrace to ece)
> 🐟 Adjust request limit

- client/src/css/LoginRegister.css
* Fixes not-centered text on login/register submit button.
> 🥨 Center login/register button text

- client/src/components/ResourcesGrid.js
- client/src/css/Home.css
- client/src/pages/Home.js
* Lessens weight of "partners in the community" by 100.
* Increases vertical spacing between resource cards.
> 🐪 Add style modifications to partner header and resource cards

- client/src/css/ResourceDetail.css
- client/src/pages/ResourceDetail.js
- client/yarn.lock
ResourceDetailed gets the resource's `recommendation` and shows that many stars out of five to indicate the resource's rating.
> Rating for a resource is indicated by stars

- client/src/components/desktop/HomeDesktop.js
- client/src/components/desktop/ResourcesFilter.js
- client/src/components/mobile/HomeMobile.js
- client/src/components/mobile/ResourcesFilterMobile.js
- client/src/css/ResourcesFilter.css
- client/src/css_mobile/ResourcesFilterMobile.css
- client/yarn.lock
Resolves #223 
Also displays a hard-coded "Find Resources" string on the homepage if the categories haven't been fetched yet instead of displaying nothing. lmk if there's a different placeholder I should change it to
> ⬅️ Align filters

- client/src/components/ResourcePreview.js
- client/src/css/ResourcePreview.css
Resolves #239 
Styling changes for resource previews
> 🎴 Restyle resource card descriptions

- api/yarn.lock
- client/src/components/ResourceCategoryFilter.js
- client/src/components/ResourceForm.js
- client/src/components/desktop/HomeDesktop.js
- client/src/components/mobile/HomeMobile.js
- client/src/pages/ResourceDetail.js
- client/src/pages/Resources.js
- client/src/pages/SavedResources.js
- client/yarn.lock
- Upgrade yarn dependencies
- Silence some lint warnings
> 💤 Upgrade yarn, silence some lint warnings

- client/src/css/ResourceDetail.css
- client/src/pages/ResourceDetail.js
- client/yarn.lock
Used momentjs to determine whether current time falls in any of the days' hours of operations.
> 🔥 Display Open Now on ResourceDetail

- client/src/components/desktop/HomeDesktop.js
- client/src/components/mobile/HomeMobile.js
- client/src/css/Home.css
- client/src/css/LoginRegister.css
- client/src/css_mobile/Home.css
- client/src/pages/Home.js
- client/yarn.lock
This PR implements these design modifications as per Chloe's request:
* Add spaces in between "Partners and Community" title and images
* Add space in between partners images
* Add ability to hover over a partner image on desktop, and see the title of that partner
* Change the login/registration error text to be yellow
* Make the transitions for testimonials changing a fade
* Make the rectangles on the testimonial carousel dots
* Change the background image of testimonials to be a gradient
> 🎨 Implement small design modifications

- client/src/components/ResourceForm.js
- client/src/components/SaveButton.js
- client/src/components/mobile/ResourceDetailMobile.js
This PR:
* Displays the state and zipcode on the mobile resource detail page
* Displays the eligibility requirements on the mobile resource detail page
* Removes some unused code in the admin form that was also causing bugs
* Changes the banner of the admin form to be either "edit" or "add" depending on what you're doing
* Removes some other unused code
> 🐛 Fix some bugs

- README.md
- api/src/appListener.js
- client/package.json
- client/public/asset/manifest.json
- client/public/index.html
- client/src/utils/api.js
- now.json
Deploy to nawc.now.sh as opposed to ymca.now.sh
> 🗞️ Deploy to nawc

- auth/src/api/index.js
> 🐛 Fix auth not working

- client/src/App.js
- client/src/components/Footer.js
- client/src/components/desktop/FooterDesktop.js
- client/src/components/mobile/FooterMobile.js
- client/src/css/Footer.css
Add a footer to all pages which will show Hack4Impact copyright and links to feedback and usage guide
Closes #264
> 👟 Add footer to display links and copyright

- client/src/components/desktop/NavigationDesktop.js
- client/src/css/Navigation.css
Resolves #236 
Line begins from the middle and expands out when moused over, the line stays there when it's the active link
> 🧙 Add navbar transition

- client/src/pages/RoleApproval.js
Fixes user sorting breaking when upgrading ant design. Also removes a bunch of code that was unnecessarily complicated as a workaround to sorting not working.
> 🐜 Fix user sorting

- .github/workflows/codeql-analysis.yml
- README.md
- api/yarn.lock
- client/yarn.lock
- Upgrade node dependencies
- Fix broken profile images on readme, now hosted with GitHub
- Add codeql scanning
> 🏔 Add codeql scanning, update readme and dependencies

- client/package.json
- client/src/components/ResourceFilterSearch.js
- client/yarn.lock
There was a search bug where if a resource with the same name existed, or for some reason a resource didn't have a category, the searchbar would bug out.  This fixes that by moving all of the logic into a separate forEach
There was also some css issues when we upgraded antd
> 🐛 Roll back antd and fix search bug

- api/yarn.lock
- client/yarn.lock
- dependabot.yml
- Add weekly dependabot PRs for all package.json
> 🤖 Dependency management

- client/src/css/ResourcesFilter.css
- client/src/css/SaveButton.css
- Update sort by link color (Closes #291)
- Move save button closer to the right (Closes #292)
> 🎨 Style changes

- .circleci/config.yml
- client/src/components/Footer.js
- client/src/components/Navigation.js
- client/src/components/ResourcesBanner.js
- client/src/components/desktop/HomeDesktop.js
- client/src/components/mobile/HomeMobile.js
- client/src/pages/Home.js
- client/src/types/models.js
- client/src/utils/api.js
- client/src/utils/mobile.js
This PR:
* Adds types to our api calls
* Adds flow to the homepage files
> 🌊 Add flow to API responses

- client/src/components/ResourceDetailCommon.js
- client/src/components/mobile/ResourceDetailMobile.js
> 🐛 Fix bug with auth on mobile resource detail

- .github/workflows/flow-coverage.yml
- client/src/components/ResourcePreview.js
- client/src/utils/determineStockPhoto.js
This PR:
* Adds the action to view flow coverage changes on files under client/src
* Adds more flow coverage to resource preview
> ➕ Add flow-coverage action

- .github/workflows/emojify-pr.yml
Adds GitHub Action which will automatically add an emoji to front of PR title if it does not exist
> 🧑🏿‍🤝‍🧑🏽 Add emojify PR workflow

- .github/workflows/flow-coverage.yml
As title - makes the bot update comments, instead of posting a new one on each push
> 👬🏽 Update flow action to v0.2

- README.md
- client/src/components/SaveButton.jsx
- client/src/components/desktop/ResourcesFilter.jsx
- client/src/components/mobile/ResourcesCatMobile.jsx
- client/src/css/ResourcesCat.css
- client/src/css/ResourcesFilter.css
- client/yarn.lock
- Fix all linting errors
- Fix README badge (Closes #312)
> 👩 ‍ General improvements

- client/src/App.jsx
- client/src/components/desktop/HomeDesktop.jsx
- client/src/components/mobile/HomeMobile.jsx
- client/src/pages/Home.jsx
* Removes multiple api calls to the same homepage api, and just called the gethomepage api at the top of the home component
* Uses [lazy loading](https://reactjs.org/docs/code-splitting.html#route-based-code-splitting) for our react router
* Right now, when you first navigate to the sight, you'll briefly just see text for "Loading...", which I'll make a task to improve (#317)
> 🧗🏼‍♀️ Improve home page load times

- api/package.json
- api/src/middleware/auth.js
- auth/README.md
- auth/package.json
- client/package.json
- client/src/components/ShareButton.jsx
- client/src/css/LoginRegister.css
- client/src/css/Navigation.css
- client/src/css/ResourceDetail.css
- client/src/utils/api.js
- client/src/utils/auth.js
See #320 - same thing but changing to nawc.vercel.app
> 👩🏽‍🤝‍👨🏿 Change production urls

- README.md
> 🧑🏿‍🚒 Add Neha to team on readme

- README.md
> 🚴 Add Ayan to README.md

- client/package.json
- client/yarn.lock
- package.json
:rocket: Ready
Add formatjs to frontend with yarn for i18n
> 🧶 Add FormatJS

- README.md
> 👩 ‍Add Luciana to readme

- README.md
> 🤿 Add license scanning

- .github/workflows/emojify-pr.yml
New release `v1.3.1` resolves all undesired behavior with emojifying a PR.
> ✊🏾 Greatly improve emojify bot

- client/src/components/ResourceManager.jsx
- client/src/css/ResourceManager.css
- client/src/pages/AdminResourceManager.jsx
- Create the sidebar for the "Manage Resources" tab
- Populate the sidebar with categories/subcategories from the get endpoint
- Style the X icon to appear as red
> 🙅🏼‍♂️ Create menu sidebar for modifying categories

- client/src/App.jsx
- client/src/components/Navigation.jsx
:rocket: Ready
This PR:
* Stores a user's language selection in local storage so they don't have to select every time they refresh/visit the site
* Fixes a bug where our UI would not reflect a user's language selection
Fixes #373
> 🏌️‍♂️ Store language selection

- client/src/components/Navigation.jsx
- client/src/components/ResourceCategoryFilter.jsx
- client/src/components/ResourcePreview.jsx
- client/src/components/ResourcesBanner.jsx
- client/src/components/ResourcesBreadcrumb.jsx
- client/src/components/mobile/ResourcesCatMobile.jsx
- client/src/utils/messages.js
:rocket: Ready
Completes resource page for translating - all Spanish translations are entered into the db. Same with navbar
You can see categories and subcategories are now translated, the breadcrumb, as well as the resource preview description
> ✨ Complete conversion to FormatJS on resources page

- client/src/components/EditCategoryModal.jsx
- client/src/components/ManageResourcesTable.jsx
- client/src/components/ResourceManager.jsx
- client/src/utils/api.js
:rocket: Ready
When categories were edited, the table would not always reflect this change and bug out - this PR fixes that by lifting the fetch resources function up.
> 🧔🏻 Sync table when editing categories

- client/src/components/ResourceForm.jsx
In success message after editing or creating resource the link to the resource is displayed and can be clicked.
> 🚣🏿‍♀️ Add link to resource form message

- api/src/api/resource.js
- client/src/pages/Resources.jsx
- client/src/utils/api.js
:rocket: Ready
This PR moves all of our resource filtering to the backend.  This can speed up filtering (as we're just relying on the server, rather than the person's own client), and this is in order to set up our backend to handle pagination (we wouldn't be able to accurately paginate if we're filtering on the frontend. Or it would be overly complicated).  Overall this is an improvement 👍 
I tested to ensure that it didn't break filtering, but feel free to pull the branch and test yourself locally.
> 👩🏿‍🌾 Change resource filtering to backend

- api/src/api/admin.js
- client/src/utils/api.js
:rocket: Ready
* Add patch endpoint to edit categories/subcategories of a resource
* Add frontend integration for that endpoint
Part of #380
> 🖊️ Add endpoint to edit resource categories

- api/src/api/admin.js
- client/src/components/Footer.jsx
- client/src/components/ResourceFilterSearch.jsx
- client/src/components/ResourceManager.jsx
- client/src/components/ResourcesBreadcrumb.jsx
- client/src/components/desktop/HomeDesktop.jsx
- client/src/components/desktop/ResourceDetail.jsx
- client/src/components/mobile/ResourceDetailMobile.jsx
- client/src/components/mobile/ResourcesCatMobile.jsx
- client/src/pages/PasswordReset.jsx
- client/src/pages/Register.jsx
- client/src/pages/ResourceUnknown.jsx
- client/src/utils/messages.js
:rocket: Ready
This includes the reset password page, footer, resource detail mobile, searchbar, and the covid-19 pop-up on the homepage. Only thing is we don't have 'contact information' for translations bc it looks like I missed that in my scraping of static text, so I appended it to the Google doc
> ♥️ Use FormatJS on the rest of the site

- client/src/components/EditHome.jsx
- client/src/components/ResourceContactForm.jsx
- client/src/components/ResourceFinancialAidForm.jsx
- client/src/components/ResourceFormCarousel.jsx
- client/src/components/ResourceInternalNotesForm.jsx
- client/src/components/ResourcePhoneNumberForm.jsx
- client/src/components/ResourcePreview.jsx
- client/src/components/ResourceReqDocsForm.jsx
- client/src/components/desktop/ResourceDetail.jsx
- client/src/components/desktop/ResourcesFilter.jsx
- client/src/components/mobile/ResourceDetailMobile.jsx
- client/src/components/mobile/ResourcesFilterMobile.jsx
- client/src/data/languages.js
- client/src/utils/languages.js
:rocket: Ready
This PR:
* As title
* Adds forced spellcheck on inputs in admin forms
Fixes #406 
Fixes #392
> 💆 Display languages in their respective language

- .github/workflows/emojify-pr.yml
> 👩🏼‍🦳 Bump emojify pr

- api/src/api/resource.js
- api/test/resource.test.js
- client/src/components/ResourceFilterSearch.jsx
- client/src/components/ResourceManager.jsx
- client/src/components/ResourcesGrid.jsx
- client/src/pages/Resources.jsx
- client/src/pages/SavedResources.jsx
- client/src/utils/api.js
- Worked on setting size and limit on aggregation 
- Edited result in all the places with get resources to take totalData
- Edited test for api (made sure it was result.totalData)
- Worked with an amazing tech lead 
Limit was set to 5
> 🌐 Add backend pagination

- .github/workflows/emojify-pr.yml
- api/src/api/resource.js
- api/test/resource.test.js
- client/src/components/ResourceFilterSearch.jsx
- client/src/components/ResourceManager.jsx
- client/src/components/ResourcesGrid.jsx
- client/src/pages/Resources.jsx
- client/src/pages/SavedResources.jsx
:rocket: Ready
Merges in backend pagination changes, and changes to responsive grid resource view.
> 🙎🏻 Merge master into production

- client/src/css/LoginRegister.css
- client/src/pages/Resources.jsx
:rocket: Ready
This wasn't enabled before, and on some devices you wouldn't be able to see the login/register button.
> ⚒️ Enable scroll on login and register

- client/src/App.jsx
- client/src/components/Navigation.jsx
- client/src/css/LoginRegister.css
- client/src/css/Translations.css
- client/src/pages/Resources.jsx
- client/src/pages/Translations.jsx
:rocket: Ready
Includes login/register scrollbar bugfix, and translation tab for admins.
> 🧙🏼‍♂️ Merge master into production

- api/src/models/homepage.js
- client/src/components/EditHome.jsx
- client/src/components/desktop/HomeDesktop.jsx
- client/src/components/mobile/HomeMobile.jsx
- client/src/pages/Home.jsx
- client/src/types/models.js
:rocket: Ready
This PR creates a testimonial model (rather than a testimonial being an array of strings) in order to assign an ID to it with mongo, to prepare for translation validation of a testimonial. This is tested to ensure the homepage and editing a homepage still works.
After pushing, I will need to merge this to prod and edit the prod database to ensure the data is in this new format.
> 🙌🏼 Create testimonial model

- client/src/components/PriorityIcon.jsx
- client/src/components/StatusTag.jsx
- client/src/css/PriorityIcon.css
- client/src/css/StatusTag.css
- client/src/pages/Translations.jsx
- client/src/utils/api.js
Created UI for translation validation table
> 🐘 Translation table

- api/src/api/admin.js
- api/src/utils/verification.js
> 🥻 Fix name not appearing for subcategories on verification table backend endpoint

- api/src/models/resource.js
- api/src/scripts/addVerifiedTranslations.js
- api/src/utils/translate.js
- api/src/utils/verification.js
- client/src/components/desktop/ResourceDetail.jsx
- client/src/components/mobile/ResourceDetailMobile.jsx
- client/src/utils/api.js
:rocket: Ready
As title - also fixes a few bugs with the verified translations table endpoint, resource detail financial aid text, and adds addition/deletion of verified translation documents when adding/deleting a resource
> ⛴️ Add script used to bulk add verified translation documents

- api/src/api/admin.js
> 🚴🏾‍♀️ Add endpoint to report error

- client/src/css/Translations.css
- client/src/pages/Translations.jsx
- client/src/utils/api.js
- Gets verification data from backend
- Shows priority and status for each translation in table
> 🏃‍♀️ Show resources in verification table

- client/src/components/Navigation.jsx
- client/src/components/ResourceCategoryFilter.jsx
- client/src/components/ResourceFormCarousel.jsx
- client/src/components/ResourcePreview.jsx
- client/src/components/ResourcesBreadcrumb.jsx
- client/src/components/SaveButton.jsx
- client/src/components/ShareButton.jsx
- client/src/components/desktop/ResourceDetail.jsx
- client/src/components/mobile/ResourceDetailMobile.jsx
- client/src/css/Antdesign.css
- client/src/css/Navigation.css
- client/src/css/ResourceDetail.css
- client/src/css/ResourcePreview.css
- client/src/css/ResourcesBreadcrumb.css
- client/src/css/ResourcesFilter.css
- Increases font sizes for the resources page
- Fixes padding / spacing for 'language switching' on the navigation bar
- Fixes spacing between icon and text in 'Save' and 'Share' buttons
- Fixes resource information overflow (issue #322)
Fixes #322
> 🚉 Add CSS fixes, improve font accessibility

- client/src/components/MapManager.jsx
- client/src/components/MapViewList.jsx
- client/src/components/MapViewModal.jsx
- client/src/components/ResourceMap.jsx
- client/src/css/MapViewModal.css
- client/src/css/ResourceMap.css
- client/src/pages/Resources.jsx
- Pipe resource information into mapview modal when clicked
- Implemented close/scroll functionality of modal
- Memoize map to not refresh when a new resource is selected
> 🗾 Integrate mapview list and modal into map tab

- api/src/api/resource.js
- client/src/components/MapManager.jsx
- client/src/components/MapViewList.jsx
- client/src/components/MapViewModal.jsx
- client/src/components/ResourceMap.jsx
- client/src/css/MapViewList.css
- client/src/css/MapViewModal.css
- client/src/css/ResourceMap.css
- client/src/pages/Resources.jsx
- client/src/utils/api.js
- Create layer within map that displays marker for each resource
- Enable zoom whenever user clicks on resource or searches for location
> 🧑🏼‍🤝‍🧑🏽 Display resource markers and implement zoom functionality

- client/src/components/ResourceFilterAutofill.jsx
- client/src/components/TranslationFormRow.jsx
- client/src/components/desktop/ResourcesFilter.jsx
- client/src/css/EditTranslations.css
- client/src/pages/EditTranslations.jsx
- client/src/pages/Resources.jsx
:rocket: Ready
As title - and also adds redirect logic when clicking submit if at least one translation is verified
I commented out some css since it was a bit wonky - i'll make an issue to fix this later
> 👨‍🔧 Add checkbox progress bar logic

- api/src/api/admin.js
- api/src/api/translation.js
- client/src/components/ResourcesBreadcrumb.jsx
- client/src/components/TranslationFormRow.jsx
- client/src/components/desktop/ResourceDetail.jsx
- client/src/components/mobile/ResourceDetailMobile.jsx
- client/src/pages/EditTranslations.jsx
- client/src/pages/Translations.jsx
- client/src/utils/api.js
:rocket: Ready
This PR:
* Adds an endpoint to edit translations and verify translations
* Adds the frontend call to the api when the translation form is submitted
* Adds an endpoint to get whether a resource is verified or not
* Toggles on the frontend to show if a resource if verified or not based on the api call
* Deletes two endpoints never used
> 🍾 Implement submission of translation form

- api/src/api/resource.js
- client/src/components/MapManager.jsx
- client/src/components/MapViewModal.jsx
- client/src/components/ResourceFilterAutofill.jsx
- client/src/components/ResourceMap.jsx
- client/src/components/ResourcesMap.jsx
- client/src/components/SaveButton.jsx
- client/src/components/desktop/ResourcesFilter.jsx
- client/src/pages/Resources.jsx
- client/src/pages/Translations.jsx
- client/src/utils/api.js
- client/src/utils/geocoding.js
- client/src/utils/savedMessages.jsx
:rocket: Ready
This PR:
* Allows mapview to be filtered by cost/language/location
* Implements the save, share, and directions button on the mapview modal
* Removes the sorting capability for mapview since it should always be sorted by closest
> 🗾 Add filtering to mapview and implement buttons on mapview modal

- api/src/api/admin.js
- api/src/api/index.js
- api/src/api/volunteer.js
- api/src/middleware/auth.js
- api/src/routes/index.js
- auth/README.md
- auth/config.yml
- client/src/App.jsx
- client/src/components/Navigation.jsx
- client/src/components/RoleApproval.jsx
- client/src/utils/api.js
- client/src/utils/auth.js
:rocket: Ready
This PR:
* Adds the NAWC volunteer role, which has access to translation verification, but not anything admin related
* Removes the "intern" role
* Allows admins to promote regular "public" users to be a "nawc volunteer", giving them access to translation verification
* Extends token duration from 1 hour to 2 hours
I tested to ensure volunteers do not have access to admin functions, while admins still have access to translation functions.
Fixes #394
> 🎅🏿 Add nawc volunteer role

- .github/workflows/emojify-pr.yml
Adds blocklist functionality that prevents emojis that aren't recognized by emoji-regex, and other improvements.
> 👩🏽‍🦰 Bump emojify

- client/src/components/ManageResourcesTable.jsx
- client/src/components/ResourceManager.jsx
:rocket: Ready
* Add column to resource manager table to display the time that the resource was last updated (sortable)
* Hopefully the date format is good enough lol
Fixes #464
> 🗓️ Add last updated column to management table

- auth/src/App.js
- client/src/components/desktop/ResourceDetail.jsx
:rocket: Ready
Button should have been wrapped in a Link to not refresh the page
Also, increases rate limit to 50 instead of 5
> 🦸‍♀️ Fix edit resource button
